/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Asus
 * Created: 8-mag-2017
 */
/*CREATE TABLE tipologiaUtenti(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256)
);
CREATE TABLE utenti (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256) UNIQUE,
    cognome VARCHAR(256),
    password VARCHAR(256) NOT NULL,
    urlProPic VARCHAR(256),
    dataNascita DATE,
    tipo INTEGER,
    FOREIGN KEY (tipo) REFERENCES tipologiaUtenti(id),
    fraseBio VARCHAR(256)
);
CREATE TABLE gruppi (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256) UNIQUE,
    descrizione VARCHAR(256),
    urlProPic VARCHAR(256),
    founder INTEGER,
    FOREIGN KEY (founder) REFERENCES utenti(id)
);
CREATE TABLE tipologiaPost(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256));
CREATE TABLE utenti_gruppi(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_u INTEGER,
    FOREIGN KEY (id_u) REFERENCES utenti(id),
    id_g INTEGER,
    FOREIGN KEY (id_g) REFERENCES gruppi(id)
);
CREATE TABLE post (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contenuto VARCHAR(256),
    tipo INTEGER,
    FOREIGN KEY (tipo) REFERENCES tipologiaPost(id),
    allegato VARCHAR(256),
    gruppo INTEGER,
    FOREIGN KEY (gruppo) REFERENCES gruppi(id),
    destinatario INTEGER,
    FOREIGN KEY (destinatario) REFERENCES utenti(id),
    autore INTEGER,
    FOREIGN KEY (autore) REFERENCES utenti(id)
);
INSERT INTO tipologiaUtenti (id, nome)
VALUES (default,
        'ADMIN');
INSERT INTO tipologiaUtenti (id, nome)
VALUES (default,
        'USER');
INSERT INTO utenti (id, nome, cognome, password, urlProPic, dataNascita, tipo, fraseBio)
VALUES (default,
        'Utente 1',
        'Cognome',
        'password1',
        'img/ok.png',
        '2017-04-24',
        1,
        'Il tempo è estremamente fragile come struttura, qualsiasi deviazione, per quanto piccola può provocare un cataclisma.');
INSERT INTO utenti (id, nome, cognome, password, urlProPic, dataNascita, tipo, fraseBio)
VALUES (default,
        'Utente 2',
        'Cognome',
        'password2',
        'img/ok.png',
        '2017-04-24',
        2,
        'Peter, mi sbagliavo, non è troppo tardi! Puoi salvare entrambi i mondi, possiamo ricominciare daccapo. Stavolta dovrai semplicemente compiere una scelta diversa, e se qualcosa andasse storto, Olivia sarebbe la nostra ancora di salvezza...');
INSERT INTO utenti (id, nome, cognome, password, urlProPic, dataNascita, tipo, fraseBio)
VALUES (default,
        'Utente 3',
        'Cognome',
        'password3',
        'img/ok.png',
        '2017-04-24',
        2,
        'Sono il comandante Shepard e questo è il mio negozio preferito sulla Cittadella.');
INSERT INTO utenti (id, nome, cognome, password, urlProPic, dataNascita, tipo)
VALUES (default,
        'Incompleto',
        NULL,
        'password',
        'img/ok.png',
        '2017-04-24',
        2);
INSERT INTO gruppi (id, nome, descrizione, urlProPic, founder)
VALUES (default,
        'Gruppo 1',
        'The Flash',
        'img/g.png',
        1);
INSERT INTO gruppi (id, nome, descrizione, urlProPic, founder)
VALUES (default,
        'Gruppo 2',
        'Fringe',
        'img/g.png',
        2);
INSERT INTO gruppi (id, nome, descrizione, urlProPic, founder)
VALUES (default,
        'Gruppo 3',
        'Mass Effect',
        'img/g.png',
        3);
INSERT INTO utenti_gruppi(id, id_u, id_g)
VALUES (default, 1, 1), (default, 1, 2), (default, 1, 3), (default, 2, 2), (default, 2, 3), (default, 3, 3);
INSERT INTO tipologiaPost (id, nome)
VALUES (default,
        'TESTO');
INSERT INTO tipologiaPost (id, nome)
VALUES (default,
        'IMMAGINE');
INSERT INTO tipologiaPost (id, nome)
VALUES (default,
        'URL');
INSERT INTO post (autore, contenuto, tipo, id, gruppo, destinatario, allegato)
VALUES(1, 'Cisco: "It looks like the Vacuum. Jesse: "Uh, what is the Vacumm? Cisco: "No Fringe on Earth-2. Noted.', 1, default, NULL, NULL, NULL),  
(2,'Ooliiviaa!',2,default,NULL,NULL,'img/o.jpg'),
(3,'Andromeda!',3,default,NULL,NULL,'https://www.masseffect.com/it-it/andromeda-initiative'),
(1,'Corri Barry, corri!',1,default,1,NULL,NULL),
(2,'Chiamano questi eventi "Lo schema", come se qualcuno facesse esperimenti usando il mondo come laboratorio! Adesso ha visto! Adesso sa!',1,default,2,NULL,NULL),
(3,'Benvenuti al Presidium, posso essere la vostra guida?',1,default,3,NULL,NULL),     
(1,'Benvenuto!',1,default,NULL,4,NULL);
CREATE TABLE utenti_utenti(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ua INTEGER,
    FOREIGN KEY (id_ua) REFERENCES utenti(id),
    id_ub INTEGER,
    FOREIGN KEY (id_ub) REFERENCES utenti(id)
);
INSERT INTO utenti_utenti(id, id_ua, id_ub)
VALUES (default, 1, 2), (default, 1, 3), (default, 2, 3), (default, 1, 4);*/
/*ALTER TABLE utenti ALTER tipo SET NOT NULL;*/
/*ALTER TABLE post ALTER tipo SET NOT NULL;*/